services:
  db:
    platform: linux/amd64
    image: mysql:8.0
    container_name: carizmi-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    command: --host-cache-size=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    ports:
      - "127.0.0.1:3306:3306" # Localhost only for security
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: 'redis:7.4-alpine'
    container_name: carizmi-redis
    ports:
      - "127.0.0.1:6379:6379" # Localhost only for security
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - redis_data:/data
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  backend:
    platform: linux/amd64
    container_name: carizmi-backend
    env_file: .env
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      ADMIN_DEFAULT_FIRSTNAME: ${ADMIN_DEFAULT_FIRSTNAME}
      ADMIN_DEFAULT_LASTNAME: ${ADMIN_DEFAULT_LASTNAME}
      ADMIN_DEFAULT_EMAIL: ${ADMIN_DEFAULT_EMAIL}
      ADMIN_DEFAULT_USERNAME: ${ADMIN_DEFAULT_USERNAME}
      JAVA_OPTS: ${JAVA_OPTS}
    secrets:
      - source: admin_password
        target: admin.default.password
    ports:
      - "8080:8080"

  frontend:
    platform: linux/amd64
    container_name: carizmi-frontend
    env_file: .env
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    restart: always
    depends_on:
      - backend
    environment:
      VITE_API_URL: ${VITE_API_URL}
      APP_ORG_NAME: ${APP_ORG_NAME}
      APP_HEADER_TITLE: ${APP_HEADER_TITLE}
      APP_HEADER_SUBTITLE: ${APP_HEADER_SUBTITLE}
      APP_LOGO_ALT: ${APP_LOGO_ALT}
      APP_COPYRIGHT: ${APP_COPYRIGHT}
    ports:
      - "8081:8080"

volumes:
  db_data:
  redis_data:

secrets:
  admin_password:
    file: ./secrets/admin_password.txt
