services:
  db:
    platform: linux/amd64
    image: mysql:8.0
    container_name: sofumar-db
    environment:
      MYSQL_DATABASE: sofumar
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: root_pwd
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306" # Localhost only for security
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: 'redis:latest'
    container_name: sofumar-redis
    ports:
      - "127.0.0.1:6379:6379" # Localhost only for security
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - redis_data:/data

  backend:
    platform: linux/amd64
    container_name: sofumar-backend
    env_file: .env
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"

  frontend:
    platform: linux/amd64
    container_name: sofumar-frontend
    env_file: .env
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    restart: always
    depends_on:
      - backend
    ports:
      - "8081:8080"

volumes:
  db_data:
  redis_data:
