/**
 * Custom Endpoint Definitions — Framework-Handled Routes
 *
 * This file contains API endpoint path constants for routes that are NOT handled
 * by a @RestController on the backend (and therefore are not auto-generated by
 * Orval from the OpenAPI spec).
 *
 * Common reasons an endpoint lives here:
 *   - The route is handled by a framework filter (e.g. Spring Security's
 *     UsernamePasswordAuthenticationFilter) rather than a @RestController,
 *     so Springdoc does not include it in openapi.json.
 *   - The route is consumed by low-level infrastructure (e.g. Axios interceptors)
 *     that cannot use the Orval-generated client functions.
 *
 * ⚠️  Before adding a new endpoint here, verify that it truly cannot be
 *     referenced via the auto-generated API clients in  src/api/generated/.
 *     If a @RestController endpoint exists, prefer the Orval-generated function.
 *
 * @see docs/API_GENERATION.md for the full code-generation pipeline documentation.
 */

// ---------------------------------------------------------------------------
// Auth — Spring Security Filter Chain
// ---------------------------------------------------------------------------

/**
 * Login endpoint handled by Spring Security's UsernamePasswordAuthenticationFilter.
 * There is no @RestController for this route — the filter reads `username` and
 * `password` directly from the request body and delegates to AuthenticationManager.
 */
export const AUTH_LOGIN = '/auth/login';

/**
 * Token refresh endpoint. Although this IS backed by AuthController.refreshToken(),
 * it is referenced directly by the Axios response interceptor in ApiClient.ts
 * (which cannot use Orval-generated functions because it IS the transport layer
 * that Orval delegates to). Defined here for single-source-of-truth path management.
 */
export const AUTH_REFRESH = '/auth/refresh';