import { describe, it, expect } from 'vitest';
import { AUTH_LOGIN, AUTH_REFRESH } from '../../../api/constants/customEndpoints';

/**
 * Unit tests for Custom Endpoint Definitions.
 *
 * These tests cover only the manually defined endpoint constants in
 * src/api/constants/customEndpoints.ts — routes handled by framework
 * filters (e.g. Spring Security) that are NOT auto-generated by Orval.
 *
 * Auto-generated endpoints (from src/api/generated/) are validated by:
 *   - OpenAPI contract drift detection in CI (backend-verify job)
 *   - TypeScript type-checking (npm run type-check)
 *   - Frontend build verification (npm run build)
 *
 * @see docs/API_GENERATION.md
 */
describe('Custom Endpoints', () => {
  describe('Auth — Framework-Handled Routes', () => {
    it('should define correct login endpoint path', () => {
      expect(AUTH_LOGIN).toBe('/auth/login');
    });

    it('should define correct refresh endpoint path', () => {
      expect(AUTH_REFRESH).toBe('/auth/refresh');
    });

    it('login and refresh should start with /auth/ prefix', () => {
      expect(AUTH_LOGIN).toMatch(/^\/auth\//);
      expect(AUTH_REFRESH).toMatch(/^\/auth\//);
    });

    it('should not have trailing slashes', () => {
      expect(AUTH_LOGIN).not.toMatch(/\/$/);
      expect(AUTH_REFRESH).not.toMatch(/\/$/);
    });
  });
});